[project]
name = "l-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.2",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
